class PaymentErrorCodes {
  static const Map<String, String> codes = {
    '0000': 'Transaction successful.',
    '1001': 'Decline by Issuer: The card issuer suspects the transaction to be fraudulent and therefore refuses.',
    '1002': 'Decline by Issuer: The card issuer indicates an issue with the card and requests contact from the consumer.',
    '1003': 'The card issuer indicates an issue with the card and requests contact from the consumer. The consumer can use another payment method. Alternatively, the consumer can try again after they resolve the issue with their bank.',
    '1004': 'Decline by Issuer: The transaction is not permitted. Either a restriction is applied by the Issuer to the cardholder, or the transaction is not permitted by law.',
    '1005': 'Decline by Issuer: The card is reported as lost and therefore cannot be accepted. Consumer is advised to try again using a different payment method.',
    '1006': 'Decline by Issuer: The card is reported as stolen and therefore cannot be accepted. Consumer is advised to try again using a different payment method.',
    '1007': 'The transaction is identified as a duplicate and therefore is not processed. Verify that the transaction elements (like the merchantOrderReference field) you send are unique or contact support.',
    '1008': 'The original referencing transaction is missing or is invalid. Reattempt only after you provide a correct referencing transaction or contact support.',
    '1009': 'The selected currency is not supported for the Merchant and therefore the transaction cannot be processed.',
    '2001': 'Restricted Card: The card issuer restricts where the card can be used. For example, because of embargoes.',
    '2002': 'Invalid Merchant ID: Either a wrong merchant account is sent, merchant values are wrong when running the 3-D Secure flow, the web service used isn\'t permitted for that merchantAccountId, or the company is not active.',
    '2003': 'The transaction amount is specified in an invalid format. For example, an invalid character such as a dollar sign or a space is used. Consumer should correct or use another payment method.',
    '2004': 'Insufficient funds in the consumer’s account. Consumer can try again after they add funds to their bank account or use another payment method.',
    '2005': 'The credited amount exceeds the amount of the referenced debit transaction.',
    '2006': 'The consumer fails to perform the 3-D Secure Authentication successfully. The consumer is advised to try again.',
    '2007': 'The 3-D Secure authentication fails because of an unknown device. The consumer is advised to try again later or use a different payment method.',
    '2008': 'The 3-D Secure authentication fails because of an unsupported device. The consumer is advised to try again later or use a different payment method.',
    '2009': 'The 3-D Secure Authentication Fequency Limit of this card is exceeded and therefore the issuing bank cannot accept the transaction. The consumer is advised to use a different payment method or contact the issuing bank.',
    '2010': 'The 3-D Secure authentication cannot be performed because no card records exist in 3-D Secure Access Control Server of the Issuer Bank. The consumer is advised to use a different payment method.',
    '2011': 'The 3-D Secure authentication results into a security failure. The consumer is advised to use a different payment method.',
    '2012': 'The 3-D Secure authentication cannot be performed because the customers card is not enrolled. The consumer is advised to contact their issuing bank or use a different payment method.',
    '2013': 'The transaction was declined by the Issuer because the maximum number of challenges is exceeded. The consumer is advised to contact their issuing bank or try a different payment method.',
    '2014': 'The Non Payment Authentication (NPA) transaction is declined by the issuer because it is not supported. Please make sure that the correct 3-D Secure data are provided in the transaction, otherwise contact support.',
    '2015': 'The Merchant Initiated Authentication (3RI) transaction was declined by the issuer because it is not supported. Please make sure that the correct 3-D Secure data are provided in the transaction, otherwise contact support.',
    '2016': 'The Issuer Bank´s Access Control Server responsible for 3-D Secure, cannot be reached at all. The consumer is advised to try again later or use a different payment method.',
    '2017': 'The Issuer bank is expecting a Decoupled 3-D Secure Authentication. Please make sure that the correct 3-D Secure data are provided in the transaction, otherwise contact support.',
    '2018': 'The transaction was declined by the Issuer because the Decoupled Authentication was not performed within expected time. The consumer is advised to try again later or use different payment method.',
    '2019': 'The transaction was declined by the Issuer because insufficient time was provided to the consumer to perform the Decoupled Authentication. Please contact support.',
    '2020': 'The transaction was declined by the Issuer because the 3-D Secure authentication was attempted but not performed by the consumer.',
    '2021': 'The Issuer Bank´s Access Control Server responsible for 3-D Secure, cannot be reached in timely fashion. The consumer was advised to try again later or use a different payment method.',
    '2022': 'Transaction declined by Issuer due to daily or monthly limits on transaction amount or count being exceeded. The consumer was advised to remove or increase any limits, use a different payment method or to contact the Issuing Bank for further instructions.',
    '3001': 'Strong Customer Authentication is required for the transaction. If the transaction is in scope of PSD2 and did not go through 3-D Secure, retry with 3-D Secure. This is also referred to as a "Soft Decline".',
    '3002': 'Decline by Issuer: The consumer is using an expired card.',
    '3003': 'The card issuer is unable to validate the card/account number, possibly because an invalid character was used, or the card is not supported by the processor.',
    '3004': 'The consumer either provides an expired card or the expiration date is invalid. Consumer is advised to use a valid expiry date or to try a different payment method.',
    '3005': 'The consumer provides an incorrect CVV. Consumer is advised to use the correct CVV or to try different payment method.',
    '3006': 'RaiAccept is unable to process the transaction due to a technical error with its processor.',
    '3007': 'RaiAccept is unable to process the transaction due to a technical error with the payment schemes.',
    '3008': 'The 3-D Secure authentication cannot be performed because of invalid 3-D Secure transaction. Please make sure that the recommended 3-D Secure data are provided in the transaction otherwise contact support.',
    '3009': 'Decline by Issuer: Low confidence on suspected risk. The consumer is advised to contact their Issuer bank.',
    '3010': 'Decline by Issuer: Medium confidence on suspected risk. The consumer is advised to contact their Issuer bank.',
    '3011': 'Decline by Issuer: High confidence on suspected risk. The consumer is advised to contact their Issuer bank.',
    '3012': 'Decline by Issuer: Very high confidence on suspected risk. The consumer is advised to contact their Issuer bank.',
    '3013': 'Decline by Issuer: The preferred authentication method is not supported. Please make sure that the correct 3-D Secure data are provided in the transaction, otherwise contact support.',
    '3014': 'Decline by Issuer: The validation of the Content Security Policy fails. Please make sure that the correct 3-D Secure data are provided in the transaction, otherwise contact support.',
    '3015': 'Unfortunately the transaction cannot be processed because the Issuing Bank was invalid or not known. The consumer is advised to try again using a different payment method.',
    '3016': 'Unfortunately the transaction cannot be processed because the Issuing Bank cannot be reached. The consumer is advised to try again using a different payment method.',
    '3017': 'The transaction was declined by the Issuer due to a possible security issue with this card. The consumer is advised verify correctness of CVV. Alternatively, they can use another payment method or address the issue with their Issuing Bank.',
    '4001': 'Generic refusal from the card issuer that has several possible causes.',
    '5001': 'There are too many transaction retries within one session.',
    '5002': 'This transaction is not permitted to cardholder. There is a risk-related rule that prevents the transaction from being completed.',
    '6001': 'The transaction cannot be inserted into the batch file for triggering capture.',
    '6002': 'There is no batch response file corresponding to the batch request for capture.',
    '6003': 'The number of transactions in the batch response file does not match the number of transactions in the corresponding batch request file for capture.',
    '6004': 'Identifier Field Missing – an important field or identifier (for example, trace_id or n-file name) is missing when trying to process the batch file and retrieve a transaction from database.',
    '6005': 'An unknown error was reported for the transaction during batch processing.',
    '6006': 'A duplicate of the batch file was sent to the processor to capture the transaction.',
    '6007': 'A duplicate of this transaction was sent to the processor in the batch file to Capture the transaction.',
    '6008': 'Technical error with the 3DS processing.',
    '6009': 'Technical error in Risk module.',
    '7001': 'The refund cannot be processed by RaiAccept because of invalid data.',
    '7002': 'The provided response from processor is missing business data critical to continue with the transaction.',
    '7003': 'The transaction was not processed due to technical error connected to Tokenizer service. The consumer can try again shortly.',
    '7004': 'There was a technical error and the transaction was not processed. The consumer can try again shortly.',
    '7005': 'There was data validation error and the transaction cannot be processed. The consumer can try again shortly.',
    '7006': 'The transaction cannot be processed within the expected time and is therefore cancelled by the Gateway. The consumer is not charged and can try again shortly.',
    '7007': 'The reversal request encounters a technical error.',
    '7008': 'Authentication is declined by the 3DS router.',
    '7009': 'The card brand is not supported for you or your acquirer bank.',
    '7010': 'There was a technical infrastructure error. The consumer account was not charged, but they can try again shortly.',
    '7011': 'There was a technical error while communication with processor. The consumer account was not charged, but they can try again shortly.',
    '9999': 'The transaction was not processed due to an unknown technical error. Please contact support.',
  };

  static String getMessage(String? code) {
    if (code == null) return 'An unknown error occurred';
    return codes[code] ?? 'An unknown error occurred (Code: $code)';
  }
}
