// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgcIvTBySVzCvHSlalh7Yyrmk6gUrVZa4',
    appId: '1:636085257748:web:b30b36ba87571c6db54901',
    messagingSenderId: '636085257748',
    projectId: 'sh-kosova',
    authDomain: 'sh-kosova.firebaseapp.com',
    storageBucket: 'sh-kosova.firebasestorage.app',
    measurementId: 'G-06P91TKDFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJVmfuw3DDUn0wNg0bocO-wl3qAZsMebI',
    appId: '1:636085257748:android:596e8b8d78104c44b54901',
    messagingSenderId: '636085257748',
    projectId: 'sh-kosova',
    storageBucket: 'sh-kosova.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzD3E178MKQETZ0tnmuxSDKAVuRuDCXJM',
    appId: '1:636085257748:ios:e7b41d9794b17656b54901',
    messagingSenderId: '636085257748',
    projectId: 'sh-kosova',
    storageBucket: 'sh-kosova.firebasestorage.app',
    iosBundleId: 'com.shein-ks.sheinKosova',
  );
}
