// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTRCBz48OWqQj16l-jCCEmA4vFzdsEzE',
    appId: '1:486355060056:web:ba8cb30d67d5b0f10e112d',
    messagingSenderId: '486355060056',
    projectId: 'student-food-takeaway',
    authDomain: 'student-food-takeaway.firebaseapp.com',
    storageBucket: 'student-food-takeaway.firebasestorage.app',
    measurementId: 'G-5TK4SHXBNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJEkuaRVvyI-xULGpnW1KOK92p0tO9CwA',
    appId: '1:486355060056:android:5fdb6520a011fb410e112d',
    messagingSenderId: '486355060056',
    projectId: 'student-food-takeaway',
    storageBucket: 'student-food-takeaway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5fzusIXjDHKbTww2zOTJh_I3GAJjyrs',
    appId: '1:486355060056:ios:08519b83c8fde9910e112d',
    messagingSenderId: '486355060056',
    projectId: 'student-food-takeaway',
    storageBucket: 'student-food-takeaway.firebasestorage.app',
    iosBundleId: 'com.example.sheinKosova.RunnerTests',
  );
}
